# Generated by Django 2.2 on 2022-09-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contentRegister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chTitle', models.CharField(max_length=255)),
                ('chName', models.CharField(max_length=255)),
                ('chTheory', models.CharField(max_length=2000)),
                ('chVideo', models.FileField(upload_to='videos/')),
                ('chExample', models.CharField(max_length=500)),
            ],
        ),
    ]
