# Generated by Django 2.2 on 2022-09-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeginnerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentregister',
            name='chVideo',
            field=models.FileField(blank=True, upload_to='videos'),
        ),
    ]
