# Generated by Django 2.2 on 2022-09-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeginnerApp', '0002_auto_20220930_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentregister',
            name='chExample',
            field=models.URLField(),
        ),
    ]
