# Generated by Django 2.2 on 2022-09-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeginnerApp', '0003_auto_20220930_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentregister',
            name='chExample',
            field=models.CharField(max_length=200),
        ),
    ]
