# Generated by Django 2.2 on 2022-10-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeginnerApp', '0005_auto_20220930_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentregister',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
