# Generated by Django 2.2 on 2022-10-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeginnerApp', '0006_contentregister_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentregister',
            name='chTheory',
            field=models.CharField(max_length=3000),
        ),
    ]
