# Generated by Django 2.2 on 2022-10-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeginnerApp', '0008_remove_contentregister_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentregister',
            name='chTheory',
            field=models.TextField(max_length=3000),
        ),
    ]
