# Generated by Django 2.2 on 2022-10-04 16:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeginnerApp', '0009_auto_20221004_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentregister',
            name='chTheory',
            field=ckeditor.fields.RichTextField(max_length=3000),
        ),
    ]
